import type { DefaultSharedModuleContext, LangiumServices, LangiumSharedServices, Module, PartialLangiumServices } from 'langium';
import { createDefaultModule, createDefaultSharedModule, inject } from 'langium';
import { MidiLangGeneratedModule, MidiLangGeneratedSharedModule } from './generated/module.js';
import { MidiLangValidator, registerValidationChecks } from './midi-lang-validator.js';

/**
 * Declaration of custom services - add your own service classes here.
 */
export type MidiLangAddedServices = {
    validation: {
        MidiLangValidator: MidiLangValidator
    }
}

/**
 * Union of Langium default services and your custom services - use this as constructor parameter
 * of custom service classes.
 */
export type MidiLangServices = LangiumServices & MidiLangAddedServices

/**
 * Dependency injection module that overrides Langium default services and contributes the
 * declared custom services. The Langium defaults can be partially specified to override only
 * selected services, while the custom services must be fully specified.
 */
export const MidiLangModule: Module<MidiLangServices, PartialLangiumServices & MidiLangAddedServices> = {
    validation: {
        MidiLangValidator: () => new MidiLangValidator()
    }
};

/**
 * Create the full set of services required by Langium.
 *
 * First inject the shared services by merging two modules:
 *  - Langium default shared services
 *  - Services generated by langium-cli
 *
 * Then inject the language-specific services by merging three modules:
 *  - Langium default language-specific services
 *  - Services generated by langium-cli
 *  - Services specified in this file
 *
 * @param context Optional module context with the LSP connection
 * @returns An object wrapping the shared services and the language-specific services
 */
export function createMidiLangServices(context: DefaultSharedModuleContext): {
    shared: LangiumSharedServices,
    MidiLang: MidiLangServices
} {
    const shared = inject(
        createDefaultSharedModule(context),
        MidiLangGeneratedSharedModule
    );
    const MidiLang = inject(
        createDefaultModule({ shared }),
        MidiLangGeneratedModule,
        MidiLangModule
    );
    shared.ServiceRegistry.register(MidiLang);
    registerValidationChecks(MidiLang);
    return { shared, MidiLang };
}
